unique =  set()

n =input("Enter any number : ")
unique.add(int(n))
n =input("Enter any number : ")
unique.add(int(n))
n =input("Enter any number : ")
unique.add(int(n))
n =input("Enter any number : ")
unique.add(int(n))
n =input("Enter any number : ")
unique.add(int(n))
n =input("Enter any number : ")
unique.add(int(n))
n =input("Enter any number : ")
unique.add(int(n))
n =input("Enter any number : ")
unique.add(int(n))

print("Sets of unique number : ",unique)